jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - "10"
      install: npm install
      script: npm run test:lint:js && npm run test:unit:js && npm run test:smoke:typescript
    - stage: build
      language: android
      dist: trusty
      android:
        components:
         - tools
         - platform-tools
         - build-tools-26.0.2
         - android-26
         - extra-google-m2repository
         - extra-android-m2repository
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      before_install:
        - yes | sdkmanager "platforms;android-26"
        - yes | sdkmanager "platforms;android-23"
        - nvm install 8
      before_script:
        - npm install
        - npm install babel-cli
        - PATH="node_modules/bin:$PATH" && npm pack
      script:
        - cd examples/plain
        - npm add ../../bugsnag-react-native-*.tgz
        - npm install
        - ./node_modules/.bin/react-native link
        - cd android
        - ./gradlew lint checkstyle assembleRelease
      licenses:
        -
    - stage: build
      language: objective-c
      env:
        - REACT_NATIVE_VERSION=0.53.0
      name: React Native 0.53.0
      os: osx
      osx_image: xcode10
      cache:
        - bundler
      install:
        - npm install
        - npm install babel-cli
      before_script:
        - PATH="node_modules/bin:$PATH" && npm pack
      script:
        - ./test/test-react-native-link-build.sh
    - stage: build
      language: objective-c
      env:
        - REACT_NATIVE_VERSION=0.59.10
      name: React Native 0.59.10
      os: osx
      osx_image: xcode10
      cache:
        - bundler
      install:
        - npm install
        - npm install babel-cli
      before_script:
        - PATH="node_modules/bin:$PATH" && npm pack
      script:
        - ./test/test-react-native-link-build.sh
    - stage: build
      language: objective-c
      name: React Native 0.61.5
      os: osx
      osx_image: xcode11
      cache:
        - bundler
      install:
        - npm install
        - npm install babel-cli
        - gem install cocoapods
      before_script:
        - PATH="node_modules/bin:$PATH" && npm pack
      script:
        - ./test/test-react-native-pod-build.sh
